# Generated by Django 6.0.1 on 2026-02-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConsignee',
            fields=[
                ('billing_consignee_id', models.AutoField(primary_key=True, serialize=False)),
                ('billing_consignee_name', models.CharField(max_length=200)),
                ('billing_consignee_phone', models.CharField(max_length=12)),
                ('billing_consignee_address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'billing_consignee_table',
            },
        ),
        migrations.CreateModel(
            name='BillingConsignor',
            fields=[
                ('billing_consignor_id', models.AutoField(primary_key=True, serialize=False)),
                ('billing_consignor_name', models.CharField(max_length=200)),
                ('billing_consignor_code', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Consignor Code')),
                ('billing_consignor_phone', models.CharField(max_length=12)),
                ('billing_consignor_gst', models.CharField(max_length=50)),
                ('billing_consignor_gsttype', models.CharField(max_length=50)),
                ('billing_consingor_address', models.CharField(max_length=100)),
                ('billing_consignor_type', models.CharField(max_length=30)),
                ('billing_consignor_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'billing_consignor_table',
            },
        ),
    ]
