# Generated by Django 6.0.1 on 2026-02-18 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('destination', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('particulars', models.CharField(max_length=100, null=True)),
                ('actual_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('charged_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('freight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lr_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unloading_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_generated', models.BooleanField(default=False)),
                ('consignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.billingconsignee')),
                ('consignor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accountapp.billingconsignor', to_field='billing_consignor_code')),
            ],
        ),
    ]
