# Generated by Django 6.0.1 on 2026-02-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0002_couriershipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(max_length=50)),
                ('courier_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'courier_table',
            },
        ),
    ]
