# Generated by Django 6.0.1 on 2026-02-19 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0003_couriermodel'),
        ('Staffapp', '0020_manifestmodel_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CnoteBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=50)),
                ('inv_freight', models.IntegerField()),
                ('inv_lr', models.IntegerField()),
                ('inv_unloading', models.IntegerField()),
                ('inv_other', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INVOICED', 'Invoiced')], max_length=50)),
                ('cnote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staffapp.cnotemodel')),
                ('consignor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accountapp.billingconsignor')),
            ],
            options={
                'db_table': 'cnote_billing',
            },
        ),
    ]
