# Generated by Django 6.0.1 on 2026-02-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0004_cnotebilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconsignee',
            name='billing_consignee_active',
            field=models.BooleanField(default=True),
        ),
    ]
