# Generated by Django 6.0.1 on 2026-02-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0005_billingconsignee_billing_consignee_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnotebilling',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
