# Generated by Django 6.0.1 on 2026-02-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0006_cnotebilling_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconsignor',
            name='billing_payment',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
