# Generated by Django 6.0.1 on 2026-02-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0007_billingconsignor_billing_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnotebilling',
            name='particulars',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
