# Generated by Django 6.0.1 on 2026-02-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0008_cnotebilling_particulars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnotebilling',
            name='payment',
        ),
    ]
