# Generated by Django 6.0.1 on 2026-02-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0009_remove_cnotebilling_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couriershipment',
            name='invoice_generated',
        ),
        migrations.AddField(
            model_name='couriershipment',
            name='status',
            field=models.CharField(choices=[('ALLOCATED', 'Allocated'), ('INV PENDING', 'INV Pending'), ('INVOICED', 'Invoiced')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cnotebilling',
            name='status',
            field=models.CharField(choices=[('INV PENDING', 'INV Pending'), ('INVOICED', 'Invoiced')], max_length=50),
        ),
    ]
