# Generated by Django 6.0.1 on 2026-02-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0010_remove_couriershipment_invoice_generated_and_more'),
        ('Adminapp', '0004_location_rural_commission_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='couriershipment',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.branch'),
        ),
        migrations.AddField(
            model_name='couriershipment',
            name='cnote_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='couriershipment',
            name='courier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.couriermodel'),
        ),
        migrations.AlterField(
            model_name='couriershipment',
            name='actual_weight',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='couriershipment',
            name='booking_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='couriershipment',
            name='charged_weight',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='couriershipment',
            name='consignor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountapp.billingconsignor', to_field='billing_consignor_code'),
        ),
        migrations.AlterField(
            model_name='couriershipment',
            name='destination',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='couriershipment',
            name='freight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='couriershipment',
            name='lr_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='couriershipment',
            name='other_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='couriershipment',
            name='qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='couriershipment',
            name='rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='couriershipment',
            name='unloading_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
