# Generated by Django 6.0.1 on 2026-02-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0011_couriershipment_branch_couriershipment_cnote_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingconsignee',
            name='billing_consignee_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billingconsignee',
            name='billing_consignee_phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
