# Generated by Django 6.0.1 on 2026-02-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0013_invoice_cnotebilling_invoice_couriershipment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cgst',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igst',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst',
            field=models.IntegerField(null=True),
        ),
    ]
