# Generated by Django 6.0.1 on 2026-02-25 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0014_invoice_cgst_invoice_igst_invoice_sgst'),
        ('Billingapp', '0003_rename_name_ledger_ledger_name_remove_ledger_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconsignor',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Billingapp.groups'),
        ),
    ]
