# Generated by Django 6.0.1 on 2026-02-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0015_billingconsignor_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='roundoff',
            field=models.IntegerField(null=True),
        ),
    ]
