# Generated by Django 6.0.1 on 2026-02-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0016_invoice_roundoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='roundoff',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
