# Generated by Django 6.0.1 on 2026-02-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0017_alter_invoice_roundoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cgst',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='igst',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sgst',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
