# Generated by Django 6.0.1 on 2026-02-25 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Customer', 'Customer'), ('Vendor', 'Vendor'), ('Expense', 'Expense'), ('Income', 'Income'), ('Bank', 'Bank'), ('Cash', 'Cash')], max_length=50)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('mode', models.CharField(blank=True, max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Billingapp.ledger')),
            ],
        ),
    ]
