# Generated by Django 6.0.1 on 2026-02-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('under', models.CharField(choices=[('Income', 'Income'), ('Asset', 'Asset'), ('Expense', 'Expense'), ('Liability', 'Liability')], max_length=50)),
            ],
        ),
    ]
