# Generated by Django 6.0.1 on 2026-02-25 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billingapp', '0002_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='name',
            new_name='ledger_name',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='type',
        ),
        migrations.AddField(
            model_name='ledger',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Billingapp.groups'),
        ),
    ]
