# Generated by Django 6.0.1 on 2026-02-25 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billingapp', '0003_rename_name_ledger_ledger_name_remove_ledger_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Billingapp.ledger')),
            ],
        ),
    ]
