# Generated by Django 6.0.1 on 2026-02-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billingapp', '0004_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='voucher_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
