# Generated by Django 6.0.1 on 2026-02-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billingapp', '0005_entry_transaction_id_entry_voucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
