# Generated by Django 6.0.1 on 2026-02-26 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0015_billingconsignor_group'),
        ('Billingapp', '0006_entry_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accountapp.invoice'),
        ),
    ]
