# Generated by Django 6.0.1 on 2026-01-09 13:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('broker_id', models.AutoField(primary_key=True, serialize=False)),
                ('broker_name', models.CharField(max_length=200)),
                ('borker_shortname', models.CharField(max_length=200)),
                ('broker_phone', models.CharField(max_length=200)),
                ('booking_type', models.CharField(max_length=200)),
                ('booking_address', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
            options={
                'db_table': 'broker_table',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_name', models.CharField(max_length=200)),
                ('comp_address', models.CharField(max_length=200)),
                ('comp_phone', models.CharField(max_length=10)),
                ('comp_email', models.EmailField(max_length=254)),
                ('comp_gst', models.CharField(max_length=200, unique=True)),
                ('comp_pan', models.CharField(max_length=200, unique=True)),
                ('msme_no', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'company_table',
            },
        ),
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('consignee_id', models.AutoField(primary_key=True, serialize=False)),
                ('consignee_name', models.CharField(max_length=200)),
                ('consignee_phone', models.CharField(max_length=10)),
                ('gst_no', models.CharField(max_length=200)),
                ('consignee_address', models.CharField(max_length=200)),
                ('consignee_is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'consignee_table',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'district_table',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('item_is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'item_table',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'state_table',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=200)),
                ('branch_code', models.CharField(max_length=200)),
                ('branch_shortname', models.CharField(max_length=200)),
                ('branch_type', models.CharField(max_length=200)),
                ('branch_phone', models.CharField(max_length=10)),
                ('branch_email', models.EmailField(max_length=254)),
                ('branch_address', models.CharField(max_length=200)),
                ('services', models.CharField(max_length=200)),
                ('branch_is_active', models.BooleanField(default=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.broker')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.company')),
            ],
            options={
                'db_table': 'branch_table',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=200)),
                ('driver_phone', models.CharField(max_length=10)),
                ('driver_address', models.CharField(max_length=200)),
                ('driver_is_active', models.BooleanField(default=True)),
                ('available_all', models.BooleanField(default=True)),
                ('driver_document', models.FileField(blank=True, null=True, upload_to='driver_documents')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.branch')),
            ],
            options={
                'db_table': 'driver_table',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=20)),
                ('branch', models.ManyToManyField(to='Adminapp.branch')),
                ('company', models.ManyToManyField(to='Adminapp.company')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.district')),
            ],
            options={
                'db_table': 'location_table',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.state'),
        ),
        migrations.CreateModel(
            name='Consignor',
            fields=[
                ('consignor_id', models.AutoField(primary_key=True, serialize=False)),
                ('consignor_name', models.CharField(max_length=200)),
                ('consignor_phone', models.CharField(max_length=200)),
                ('gst_no', models.CharField(max_length=200)),
                ('gst_type', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('billing_address', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('lr_charge', models.IntegerField()),
                ('consignor_is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.item')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.state')),
            ],
            options={
                'db_table': 'consignor_table',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_no', models.CharField(max_length=20)),
                ('vehicle_is_active', models.BooleanField(default=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.branch')),
            ],
            options={
                'db_table': 'vehicle_table',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.branch')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user_table',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
