# Generated by Django 6.0.1 on 2026-01-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
