# Generated by Django 6.0.1 on 2026-02-04 13:36

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='booking_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('TOPAY', 'Topay'), ('PAID', 'Paid'), ('CREDIT', 'Credit')], max_length=50),
        ),
    ]
