# Generated by Django 6.0.1 on 2026-01-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_branch_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.CharField(max_length=200),
        ),
    ]
