# Generated by Django 6.0.1 on 2026-02-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_alter_broker_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='category',
            field=models.CharField(blank=True, choices=[('NORTH', 'North'), ('CENTRAL', 'Central'), ('SOUTH', 'South')], max_length=10, null=True),
        ),
    ]
