# Generated by Django 6.0.1 on 2026-02-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_alter_branch_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='rural_commission_percentage',
            field=models.FloatField(default=0),
        ),
    ]
