# Generated by Django 6.0.1 on 2026-01-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_alter_location_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
