# Generated by Django 6.0.1 on 2026-01-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0004_usermodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignor',
            name='is_manual',
            field=models.BooleanField(default=True),
        ),
    ]
