# Generated by Django 6.0.1 on 2026-01-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0005_consignor_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignor',
            name='pod_use',
            field=models.BooleanField(default=False),
        ),
    ]
