# Generated by Django 6.0.1 on 2026-01-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0006_consignor_pod_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='shortname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
