# Generated by Django 6.0.1 on 2026-01-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0008_location_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_card',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
