# Generated by Django 6.0.1 on 2026-01-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0009_vehicle_fuel_card_vehicle_fuel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignor',
            name='item',
        ),
        migrations.AddField(
            model_name='consignor',
            name='items',
            field=models.ManyToManyField(to='Adminapp.item'),
        ),
        migrations.RemoveField(
            model_name='consignor',
            name='state',
        ),
        migrations.AddField(
            model_name='consignor',
            name='state',
            field=models.ManyToManyField(to='Adminapp.state'),
        ),
    ]
