# Generated by Django 6.0.1 on 2026-01-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0010_remove_consignor_item_consignor_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignor',
            name='state',
            field=models.ManyToManyField(to='Adminapp.location'),
        ),
    ]
