# Generated by Django 6.0.1 on 2026-01-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0011_alter_consignor_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignor',
            name='consignor_code',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True, verbose_name='Consignor Code'),
        ),
    ]
