# Generated by Django 6.0.1 on 2026-01-19 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0012_consignor_consignor_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotation_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.PositiveIntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.consignor')),
                ('item', models.ManyToManyField(to='Adminapp.item')),
                ('location', models.ManyToManyField(to='Adminapp.location')),
            ],
            options={
                'db_table': 'quotation_table',
            },
        ),
    ]
