# Generated by Django 6.0.1 on 2026-01-20 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0013_quotation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
