# Generated by Django 6.0.1 on 2026-01-20 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0014_delete_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotation_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.consignor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adminapp.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adminapp.location')),
            ],
            options={
                'db_table': 'quotation_table',
                'unique_together': {('agent', 'location', 'item')},
            },
        ),
    ]
