# Generated by Django 6.0.1 on 2026-01-23 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0015_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.branch'),
        ),
    ]
