# Generated by Django 6.0.1 on 2026-01-29 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CnoteModel',
            fields=[
                ('cnote_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reference_no', models.CharField(max_length=30)),
                ('payment', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered')], default='NEW', max_length=20)),
                ('cnote_number', models.CharField(editable=False, max_length=20, null=True, unique=True, verbose_name='CNote Number')),
                ('invoice_no', models.CharField(max_length=20, null=True)),
                ('invoice_amt', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('lr_charge', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pickup_charge', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('hamali_charge', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unloading_charge', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('door_delivery', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('other_charge', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('delivery_type', models.CharField(max_length=30)),
                ('actual_weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('charged_weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_item', models.PositiveIntegerField()),
                ('freight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('booking_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_cnotes', to='Adminapp.branch')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adminapp.consignee')),
                ('consignor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adminapp.consignor')),
                ('delivery_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_cnotes', to='Adminapp.branch')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adminapp.location')),
            ],
            options={
                'db_table': 'cnote_table',
            },
        ),
        migrations.CreateModel(
            name='CnoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adminapp.item')),
                ('cnote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Staffapp.cnotemodel')),
            ],
            options={
                'db_table': 'cnote_item_table',
            },
        ),
    ]
