# Generated by Django 6.0.1 on 2026-01-21 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adminapp', '0015_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CnoteModel',
            fields=[
                ('cnote_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reference_no', models.CharField(max_length=30)),
                ('payment', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=50)),
                ('invoice_no', models.CharField(max_length=20)),
                ('invoice_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lr_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hamali_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unloading_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('door_delivery', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_type', models.CharField(max_length=30)),
                ('actual_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charged_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_item', models.PositiveIntegerField()),
                ('freight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adminapp.branch')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adminapp.consignee')),
                ('consignor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adminapp.consignor')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adminapp.item')),
            ],
            options={
                'db_table': 'cnote_table',
            },
        ),
    ]
