# Generated by Django 6.0.1 on 2026-01-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnotemodel',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('RECEIVED', 'Received'), ('SHIPPED', 'Shipped'), ('OUT FOR DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered')], default='NEW', max_length=20),
        ),
    ]
