# Generated by Django 6.0.1 on 2026-01-21 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0015_quotation'),
        ('Staffapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnotemodel',
            name='items',
        ),
        migrations.CreateModel(
            name='CnoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cnote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Staffapp.cnotemodel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adminapp.item')),
            ],
            options={
                'db_table': 'cnote_item_table',
            },
        ),
    ]
