# Generated by Django 6.0.1 on 2026-01-21 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0015_quotation'),
        ('Staffapp', '0002_remove_cnotemodel_items_cnoteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnotemodel',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adminapp.location'),
        ),
    ]
