# Generated by Django 6.0.1 on 2026-01-30 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
        ('Staffapp', '0002_alter_cnotemodel_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cnotemodel',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cnotemodel',
            name='received_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_cnotes', to='Adminapp.branch'),
        ),
        migrations.AddField(
            model_name='cnotemodel',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_cnotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
