# Generated by Django 6.0.1 on 2026-01-31 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
        ('Staffapp', '0003_cnotemodel_received_at_cnotemodel_received_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestModel',
            fields=[
                ('manifest_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('manifest_type', models.CharField(choices=[('BRANCH', 'Branch Transfer'), ('DELIVERY', 'Delivery')], max_length=20)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Adminapp.branch')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adminapp.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Adminapp.vehicle')),
            ],
            options={
                'db_table': 'manifest_table',
            },
        ),
        migrations.AddField(
            model_name='cnotemodel',
            name='manifest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cnotes', to='Staffapp.manifestmodel'),
        ),
    ]
