# Generated by Django 6.0.1 on 2026-01-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0003_alter_cnotemodel_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnotemodel',
            name='actual_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cnotemodel',
            name='charged_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cnotemodel',
            name='door_delivery',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cnotemodel',
            name='hamali_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cnotemodel',
            name='invoice_amt',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cnotemodel',
            name='invoice_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cnotemodel',
            name='lr_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cnotemodel',
            name='other_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cnotemodel',
            name='pickup_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cnotemodel',
            name='unloading_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
