# Generated by Django 6.0.1 on 2026-01-23 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0017_alter_usermodel_branch'),
        ('Staffapp', '0004_alter_cnotemodel_actual_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnotemodel',
            name='branch',
        ),
        migrations.AddField(
            model_name='cnotemodel',
            name='booking_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_cnotes', to='Adminapp.branch'),
        ),
        migrations.AddField(
            model_name='cnotemodel',
            name='delivery_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_cnotes', to='Adminapp.branch'),
        ),
    ]
