# Generated by Django 6.0.1 on 2026-02-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0004_manifestmodel_cnotemodel_manifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnotemodel',
            name='eway_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
