# Generated by Django 6.0.1 on 2026-01-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0005_remove_cnotemodel_branch_cnotemodel_booking_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnotemodel',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered')], default='NEW', max_length=20),
        ),
    ]
