# Generated by Django 6.0.1 on 2026-02-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0005_cnotemodel_eway_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnotemodel',
            name='consignee_phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
