# Generated by Django 6.0.1 on 2026-02-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0006_cnotemodel_consignee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnotemodel',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('RECEIVED', 'Received'), ('SHIPPED', 'Shipped'), ('OUT FOR DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('Cancelled', 'Cancelled')], default='NEW', max_length=20),
        ),
    ]
