# Generated by Django 6.0.1 on 2026-01-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0006_cnotemodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnotemodel',
            name='cnote_number',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True, verbose_name='CNote Number'),
        ),
    ]
