# Generated by Django 6.0.1 on 2026-02-08 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_alter_broker_booking_type'),
        ('Staffapp', '0007_alter_cnotemodel_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CnoteTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Adminapp.branch')),
                ('cnote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='Staffapp.cnotemodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('manifest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Staffapp.manifestmodel')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
