# Generated by Django 6.0.1 on 2026-02-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0009_cnotemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnotemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
