# Generated by Django 6.0.1 on 2026-02-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0010_cnotemodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
