# Generated by Django 6.0.1 on 2026-02-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0011_manifestmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnotemodel',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('DELIVERED', 'Delivered'), ('TOPAY_RECEIVABLE', 'To Pay Receivable'), ('CREDIT_ALLOCATED', 'Credit Invoice Allocation')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cnotemodel',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
