# Generated by Django 6.0.1 on 2026-02-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0012_cnotemodel_delivery_status_cnotemodel_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnotemodel',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('RECEIVED', 'Received'), ('SHIPPED', 'Shipped'), ('OUT FOR DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('Cancelled', 'Cancelled'), ('RETURN', 'Return')], default='NEW', max_length=20),
        ),
    ]
