# Generated by Django 6.0.1 on 2026-02-12 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_alter_branch_category'),
        ('Staffapp', '0013_alter_cnotemodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.company')),
            ],
            options={
                'unique_together': {('branch', 'company')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_zone', models.CharField(choices=[('NORTH', 'North'), ('CENTRAL', 'Central'), ('SOUTH', 'South')], max_length=20)),
                ('percentage', models.FloatField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.company')),
            ],
            options={
                'unique_together': {('branch', 'company', 'from_zone')},
            },
        ),
    ]
