# Generated by Django 6.0.1 on 2026-02-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0014_bookingcommission_deliverycommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnotemodel',
            name='booking_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cnotemodel',
            name='delivery_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='deliverycommission',
            name='deduction_percentage',
            field=models.FloatField(default=0),
        ),
    ]
