# Generated by Django 6.0.1 on 2026-02-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0015_cnotemodel_booking_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcommission',
            name='lr_commission',
            field=models.FloatField(default=0),
        ),
    ]
