# Generated by Django 6.0.1 on 2026-02-15 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0004_location_rural_commission_percentage'),
        ('Staffapp', '0017_manifestmodel_loaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestmodel',
            name='from_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manifests_sent', to='Adminapp.branch'),
        ),
    ]
