# Generated by Django 6.0.1 on 2026-02-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staffapp', '0018_manifestmodel_from_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestmodel',
            name='manifest_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
